name: Go Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.1

    - name: Pull and run build in Docker container
      run: |
        docker pull sippylabs/rtpproxy:latest

    - name: Build
      run: |
        make

    - name: Test
      run: |
        docker run --rm -v ${{ github.workspace }}:${{ github.workspace }} -e PATH \
         -e WORKSPACE=${{ github.workspace }} --entrypoint /bin/sh sippylabs/rtpproxy:latest -c \
         'set -e; cd ${WORKSPACE}; apt install -y python3; ln -sf `which python3` /usr/local/bin/python; ${WORKSPACE}/scripts/travis/test_run.sh'
